plugins {
    id 'com.android.application'
}

android {
    namespace 'com.engine.minecraftclone'
    compileSdk 34
    ndkVersion "26.1.10909125"

    defaultConfig {
        applicationId "com.engine.minecraftclone"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        externalNativeBuild {
            cmake {
                cppFlags "-std=c++20"
                arguments "-DANDROID_STL=c++_shared"
            }
        }
    }

    // إعدادات التوقيع الرقمي للـ APK لضمان تثبيته على أي هاتف
    signingConfigs {
        debug {
            storeFile file("${System.getProperty('user.home')}/.android/debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            signingConfig signingConfigs.debug // يوقعه بنفس المفتاح حتى لو تم بناؤه Release
            minifyEnabled false
        }
    }

    externalNativeBuild {
        cmake {
            path "../../CMakeLists.txt"
        }
    }

    sourceSets {
        main {
            assets.srcDirs = ['../../res']
        }
    }
}
